### ISSUE TITLE
unknown type name 'bit'

### ISSUE THREAD

**Issue by adrian-elian** [jamarju/livolo-firmware#1]
Hi, 

I have loaded the project and when i tried to compile i got the error:  In file included from uart.c:4:
./uart.h:15:1: error: unknown type name 'bit'

I'm using MPLAB X IDE 5.05 with XC8 installed.

what could be the issue here? 

*** Update ***
I found the problem. The C Standard setting in XC8 Global options was set to C99. Moved it to C90 and it works perfectly. Now my only problem is that when i want to program the livolo switch, i get the error: "Cannot program a production build to a debug header." .. Hmm i need to do more digging... 

*** Update 2 ***
The problem was occuring because the debug header was enabled in my config. I disabled it by going to Project Properties -> Configuration -> Under "Supported Debug Header" I selected "None". 
-> Make and Program device and everything was ok. 

This issue can now be closed as the programming works fine. I will open another issue with another problem i'm facing after flash, in the hopes of also helping other people in the future. 

Thanks, 
Regards.

**Comment by jamarju** [comment]
Thanks for the update. Please post back how you fixed it in case it helps others.
